[build]
  publish = "out/landing"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Form handling configuration
[[forms]]
  name = "contact"

# Redirect rules
[[redirects]]
  from = "/thank-you"
  to = "/"
  status = 200

# Handle SPA routing for Next.js static export
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

# Form notifications - Configure these in Netlify dashboard
# Go to Site settings > Forms > Form notifications
# Add email notification with your desired email address
